language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev
script:
  - make
  - make test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - lordaku@gmail.com
    on_success: change
    on_failure: always